# curl --location --request POST 'http://localhost:6666/alert'
#--header 'Content-Type: application/json'
#--data-raw '{
#	"chat_id": -680565814,
#	"msg": "secret"
#}'
POST http://localhost:6666/alert
Content-Type: application/json

{
	"chat_id": 11111,
	"msg": "secret"
}

###

# curl --location --request POST 'http://localhost:6666/alert'
#--header 'Content-Type: application/json'
#--data-raw '{
#	"msg": "secret"
#}'
POST http://localhost:6666/alert
Content-Type: application/json

{
	"msg": "secret"
}

### health
GET {{baseUrl}}/health
Accept: application/json

###

